all:
	convert monkey_icon_white_circle.png -resize 1024x1024 icon_512x512@2x.png
	convert monkey_icon_white_circle.png -resize 512x512 icon_512x512.png
	convert monkey_icon_white_circle.png -resize 256x256 icon_256x256.png
	convert monkey_icon_white_circle.png -resize 128x128 icon_128x128.png
	convert monkey_icon_white_circle.png -resize 64x64 icon_32x32@2x.png
	convert monkey_icon_white_circle.png -resize 32x32 icon_32x32.png
	convert monkey_icon_white_circle.png -resize 16x16 icon_16x16.png
	cp icon_512x512.png icon_1024x1024.png
	cp icon_512x512.png icon_1024x1024@2.png
	cp icon_512x512.png icon_256x256@2x.png
	cp icon_256x256.png icon_128x128@2x.png
	cp icon_32x32.png icon_16x16@2x.png
